### ISSUE TITLE
Video Outputs in ReadMe file

### ISSUE THREAD

**Issue by mkara44** [mkara44/liveportrait_talker#1]
https://github.com/user-attachments/assets/63496204-3d2c-47d1-aec5-f6b2425b602f

https://github.com/user-attachments/assets/b771aee7-96f7-4e93-ae30-114e872d0519

https://github.com/user-attachments/assets/1e0a743c-c608-4217-94c4-6736badee171

https://github.com/user-attachments/assets/11ec02ed-cee0-4e83-bd4f-8356cdd37035

**Comment by mkara44** [comment]
https://github.com/user-attachments/assets/d7cbd241-c379-4c30-8b68-ae2f9026f8f9

**Comment by nitinmukesh** [comment]
How are you getting good results. I tried

https://github.com/mkara44/liveportrait_talker/issues/8

**Comment by mkara44** [comment]
Hi, as you realised and I mention in ReadMe my pretrained model is not generating outputs stable everytime. However, I can say that it achieves better results if the source image lip is closed, unfortunately not everytime.
