### ISSUE TITLE
models

### ISSUE THREAD

**Issue by zachysaur** [mkara44/liveportrait_talker#2]
you didnt mentioned in what folders models should be

**Comment by mkara44** [comment]
Hi,

You are right, I forgot to mention folder structure. For now you can see folder structure below. You also need to update model paths from config files. I will update the ReadMe file later. 

- assets
- pretrained_models
* liveportrait
* * _Liveportrait related models should be here. They can be downloaded from official repository. Also same folder structure is used._ 
* sadtalker
* * _Sadtalker safetensor model should be here. It can be downloaded from official repository._ 
 * mappingnet_basic_64inp_onlylip.pt

I will be close thise issure after updates.

**Comment by mkara44** [comment]
Hi again, sh script is added to create folder structure and download pretrained models automatically.
