### ISSUE TITLE
config yml CPU CUDA

### ISSUE THREAD

**Issue by clocad** [mkara44/liveportrait_talker#6]
when set to - cuda - gives this error

(venv) D:\liveportrait_talker>python inference.py --config_path config.yaml --source_path "D:\liveportrait_talker\Face\Tarkan1080.jpg" --audio_path "D:\liveportrait_talker\Audio\MyMemory.wav" --save_path "D:\liveportrait_talker\Output"
Config File is loaded succesfully!
Traceback (most recent call last):
  File "D:\liveportrait_talker\inference.py", line 78, in <module>
    main(args)
  File "D:\liveportrait_talker\inference.py", line 23, in main
    preprocess = Preprocess(device=cfg.device,
  File "D:\liveportrait_talker\src\modules\preprocess.py", line 28, in __init__
    self.sd_prep = SadTalkerPreprocess(device=device,
  File "D:\liveportrait_talker\src\utils\preprocess\sadtalker_preprocess.py", line 20, in __init__
    self.detector = init_alignment_model('awing_fan', device=device, model_rootpath=model_path)
  File "D:\liveportrait_talker\src\utils\preprocess\helper.py", line 147, in init_alignment_model
    model.load_state_dict(torch.load(model_path, map_location=device)['state_dict'], strict=True)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1272, in _legacy_load
    result = unpickler.load()
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1205, in persistent_load
    obj = restore_location(obj, location)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1313, in restore_location
    return default_restore_location(storage, map_location)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 393, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with gpu)

when set to - cpu -  this error

(venv) D:\liveportrait_talker>python inference.py --config_path config.yaml --source_path "D:\liveportrait_talker\Face\Tarkan1080.jpg" --audio_path "D:\liveportrait_talker\Audio\MyMemory.wav" --save_path "D:\liveportrait_talker\Output"
Config File is loaded succesfully!
D:\liveportrait_talker\venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\liveportrait_talker\venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" to D:\liveportrait_talker\pretrained_models\sadtalker\detection_Resnet50_Final.pth

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 104M/104M [01:19<00:00, 1.37MB/s]
Traceback (most recent call last):
  File "D:\liveportrait_talker\inference.py", line 78, in <module>
    main(args)
  File "D:\liveportrait_talker\inference.py", line 23, in main
    preprocess = Preprocess(device=cfg.device,
  File "D:\liveportrait_talker\src\modules\preprocess.py", line 31, in __init__
    self.__load_3dmm_coeff_model(sadtalker_checkpoint_path=sadtalker_checkpoint_path)
  File "D:\liveportrait_talker\src\modules\preprocess.py", line 34, in __load_3dmm_coeff_model
    checkpoint = safetensors.torch.load_file(sadtalker_checkpoint_path)
  File "D:\liveportrait_talker\venv\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:

**Comment by mkara44** [comment]
Did you download the pretrained models?

**Comment by clocad** [comment]
yes, now it gives this error 


(venv) D:\liveportrait_talker>python inference.py --config_path config.yaml --source_path "D:\liveportrait_talker\Face\Tarkan1080.jpg" --audio_path "D:\liveportrait_talker\Audio\MyMemory.wav" --save_path "D:\liveportrait_talker\Output"
Config File is loaded succesfully!
D:\liveportrait_talker\venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\liveportrait_talker\venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "D:\liveportrait_talker\inference.py", line 78, in <module>
    main(args)
  File "D:\liveportrait_talker\inference.py", line 34, in main
    map2lp = Map2LivePortrait(device=cfg.device,
  File "D:\liveportrait_talker\src\modules\map2lp.py", line 13, in __init__
    self.mapping.load_state_dict(torch.load(mappingnet_model_path))
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1446, in _load
    result = unpickler.load()
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1416, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 1390, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 390, in default_restore_location
    result = fn(storage, location)
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\serialization.py", line 307, in _mps_deserialize
    return obj.mps()
  File "D:\liveportrait_talker\venv\lib\site-packages\torch\storage.py", line 144, in mps
    return torch.UntypedStorage(self.size(), device="mps").copy_(self, False)
RuntimeError: torch.UntypedStorage(): Storage device not recognized: mps

(venv) D:\liveportrait_talker>

**Comment by clocad** [comment]
i installed pytorch with command

install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

but - requirements.txt - is uninstalling it

**Comment by mkara44** [comment]
I updated requirements.txt. Now ,it won't delete installed PyTorch or install PyTorch. You can follow the instruction from readme file.

**Comment by clocad** [comment]
ok l ll try

**Comment by clocad** [comment]
![cmd_TmSf4nuCqJ](https://github.com/user-attachments/assets/20226d66-9a06-4386-ad83-3017b3627dc4)

**Comment by clocad** [comment]
![cmd_cCV7hG57eM](https://github.com/user-attachments/assets/95cfd4a3-7f20-4f8b-b98b-feb559d7376c)

**Comment by clocad** [comment]
![cmd_yrkzwm8yJl](https://github.com/user-attachments/assets/886673f7-f7bd-43b2-af92-03b0927ac250)


wheel needs to be installed i guess

**Comment by clocad** [comment]
pip install wheel - then - pip install requirements

![cmd_zkJpl6BnCH](https://github.com/user-attachments/assets/02f07840-83bd-4403-802c-841548284d09)

**Comment by clocad** [comment]
Visual Studio c++ build tools - needed it says

**Comment by clocad** [comment]
i have it ready, will install now

**Comment by clocad** [comment]
![cmd_JakngkVw8p](https://github.com/user-attachments/assets/4ef0a042-3720-4766-ae8b-377c9f5cfb03)

no errors for now

**Comment by clocad** [comment]
set config yml - cuda 

![cmd_NJExWOmqfU](https://github.com/user-attachments/assets/30d0f648-5478-4de0-b3f1-496b0948bb28)

**Comment by clocad** [comment]
set device in config yml to - cpu

![cmd_5F1dwzmzFT](https://github.com/user-attachments/assets/ab5c2c81-2313-4ac9-9440-f4d54065aef1)

**Comment by clocad** [comment]
![notepad++_GOQS3ITXTN](https://github.com/user-attachments/assets/607a7b08-ec6a-48d9-8475-8422a4eca60a)

**Comment by clocad** [comment]
![notepad++_kHufBEcJzE](https://github.com/user-attachments/assets/2d1d7906-b12b-48fe-bec5-18c19ce1cb93)
![cmd_FTwM8LUZPJ](https://github.com/user-attachments/assets/bc6a0131-7ea9-4dfe-b896-72ffa9340fa1)

**Comment by mkara44** [comment]
it should be work when device is cpu, also fps must be 25.

**Comment by clocad** [comment]
![notepad++_MRL1lTEhYl](https://github.com/user-attachments/assets/4cbaa5c5-c043-4cbd-b98f-df713f1dd64a)
![cmd_irQYDBY5o4](https://github.com/user-attachments/assets/06e89a1d-f8a8-46e3-9226-9cf6ed3c22b5)

**Comment by mkara44** [comment]
You are right, I updated the code, could you please try again?

**Comment by clocad** [comment]
![cmd_XoFUOTzhml](https://github.com/user-attachments/assets/0b18c8e2-3bc4-4603-abb1-ff6415cddfb0)

cloned repo, then installed pytorch, then requirements

**Comment by kd-mustafa** [comment]
Pytorch should have installed numpy. Can you try to install numpy first then run the requirements.txt command.

**Comment by mkara44** [comment]
Pytorch should have installed the numpy. Can you install numpy, then run the requirements.txr command?

**Comment by clocad** [comment]
yeah i did, pip install numpy, it sayd requirement already met, 
lws==1.2.8    this line makes trouble

**Comment by clocad** [comment]
![cmd_wgPfvd407i](https://github.com/user-attachments/assets/40ddf61b-e1b7-44a6-89ec-a29015f1c2f2)

pip install lws==1.2.8

**Comment by kd-mustafa** [comment]
What is your python version? Also, can you import numpy?

**Comment by mkara44** [comment]
What is your python version? Also, can you import numpy?

**Comment by clocad** [comment]
which version of python it is needed?, then i will redo venv with correct version

**Comment by clocad** [comment]
![cmd_XTTfd3KdnR](https://github.com/user-attachments/assets/a50d9ce5-e1d5-4962-b72b-6e28647f5c49)

pip install facexlib==0.3.0

**Comment by clocad** [comment]
![cmd_enLyUl3gME](https://github.com/user-attachments/assets/2e711334-b696-465d-86d0-3270c4185a05)

pip install kornia==0.7.3

**Comment by clocad** [comment]
![cmd_PLzXYoaPbb](https://github.com/user-attachments/assets/f28cf06d-8c45-4ebb-831e-1453e76b6f64)

pip install librosa==0.10.1

**Comment by clocad** [comment]
![cmd_QSUnkclq3r](https://github.com/user-attachments/assets/f5afd60c-e3a1-4982-a8c9-19886df4d807)

pip install lws==1.2.8

this is error message

**Comment by mkara44** [comment]
Code works fine on Python 3.10. It is weird that same error occurrd after numpy installation. I am not sure that you are installing libraries to virtual environment. Could you please install libraries using `python -m pip install -r requirements.txt`

**Comment by clocad** [comment]
it was python version 3.12 because i installed miniconda, so i will fix it and restart with version 3.10

**Comment by clocad** [comment]
i did it, installation went without any errors

**Comment by clocad** [comment]
set device to CUDA in config yml

![cmd_DT6kCGlSI1](https://github.com/user-attachments/assets/62d7da69-aa0e-4dc8-b86f-4b689eb4df85)

**Comment by clocad** [comment]
i guess now it is working 

![cmd_PUnQm7w5go](https://github.com/user-attachments/assets/6bbcef83-ef68-4441-af69-88df83155e4d)

**Comment by clocad** [comment]
ffmpeg needs to be installed

**Comment by clocad** [comment]
have to delete previous files - extracted images

![cmd_1Dn5HSYlm7](https://github.com/user-attachments/assets/7ae6b996-fa4f-4b8b-bb8c-6442e832c0c0)

**Comment by mkara44** [comment]
I assume that there is not tmp folder, I updated code to check before creating new one, you can pull and use it.
