### ISSUE TITLE
some Error generating

### ISSUE THREAD

**Issue by clocad** [mkara44/liveportrait_talker#7]
i deleted prevously generated, extracted images, in source images folder

![cmd_stbK949kAu](https://github.com/user-attachments/assets/bfc10ffc-54d7-4996-a27e-81fd9f83a5fa)

**Comment by mkara44** [comment]
This is because I used linux commands in code and you are using windows. I updated code to make this process more global, you can pull and use it.

**Comment by clocad** [comment]
same error after git pull

![K8ZSfN4oRv](https://github.com/user-attachments/assets/2ccd1d42-d194-478e-b661-f3a3e05d7944)

**Comment by clocad** [comment]
yeah and this time it didnt created images in Source images folder - creating Subfolder, as it was previously

**Comment by mkara44** [comment]
Probably tmp folder is deleted. I guess windows ffmpeg uses different type of command for getting all images in the folder. I don't have Windows, therefore I can't try. I updated the code, can you pull and try again?

**Comment by clocad** [comment]
![cmd_Cq76kkCvQ8](https://github.com/user-attachments/assets/039fe974-6859-4817-b491-29e5f446cb03)

**Comment by mkara44** [comment]
I change saving technique; using imageio to save results instead of ffmpeg. Could you please pull and try again? Also you need to install imageio==2.34.2 library.

**Comment by clocad** [comment]
![cmd_dAaMnfrngp](https://github.com/user-attachments/assets/be30a836-42f4-4f6f-a05a-a9c6e20d0a70)

![cmd_nrsAZSqcOR](https://github.com/user-attachments/assets/b7680f65-754d-4809-ace0-13c3102224a8)

**Comment by mkara44** [comment]
Yes, you must install them.
